// mie-detail/shared/core/header/index.tsx
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, useRef } from "react";
import styles from "./header.module.scss";

export interface HeaderComponentProps {}

export default function HeaderComponent(props: HeaderComponentProps) {
  const [openMenu, setOpenMenu] = useState(false);
  const [openSearchBox, setSearchBox] = useState(false);
  const [background, setBackground] = useState(false);
  const inputSearchRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (openSearchBox) {
      inputSearchRef.current?.focus();
    } else {
      inputSearchRef.current?.blur();
    }
  }, [openSearchBox]);

  useEffect(() => {
    const onScroll = () => {
      let number = document.scrollingElement?.scrollTop || 0;
      if (number > 109 && !background) {
        setBackground(true);
      }
      if (number <= 109 && background) {
        setBackground(false);
      }
    };
    document.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      document.removeEventListener("scroll", onScroll);
    };
  }, [background]);

  return (
    <header
      className={styles.header + " " + (background ? styles["bg-white"] : "")}
    >
      <div className={styles["header-content"]}>
        <div className={styles.left}>
          <a id={styles.logo} href="/">
            <Image
              src={"/image/logo_wht@3x.svg"}
              alt=""
              fill
              className={styles.image}
            />
          </a>
        </div>
        <div className={styles.right}>
          <ul>
            <li
              className={
                styles["search-box"] +
                " " +
                (openSearchBox ? styles.active : "")
              }
            >
              <input
                type="text"
                className={styles["search-text"]}
                placeholder="Type to search..."
                ref={inputSearchRef}
              />
              <button
                className={styles.icon + " " + styles["search-btn"]}
                onClick={() => setSearchBox(!openSearchBox)}
              >
                <p className={styles["container-image"]}>
                  <Image
                    src={"/image/icons/ic_search-w.svg"}
                    alt=""
                    fill
                    className={styles.image}
                  />
                </p>
              </button>
            </li>
            <li>
              <div className={styles.toggle}>
                <div
                  className={
                    styles["toggle-button"] + " " + (openMenu ? styles.on : "")
                  }
                  onClick={() => setOpenMenu(!openMenu)}
                >
                  <span></span>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div className={styles["side-nav"] + " " + (openMenu ? styles.open : "")}>
        <div
          className={styles["close-side-nav"]}
          onClick={() => setOpenMenu(!openMenu)}
        >
          <Image
            src={"/image/icons/ic_close.svg"}
            alt="close-side-nav"
            fill
            className={styles.image}
          />
        </div>
        <h2 className={styles["side-nav__title"]}>Menu</h2>
        <p className={styles["side-nav__desc"]}>メニュー</p>
        <ul className={styles["side-nav__list"]}>
          <li className={styles.item}>
            <Link href="" data-text="item1">
              item1
            </Link>
          </li>
          <li className={styles.item}>
            <Link href="" data-text="item2">
              item2
            </Link>
          </li>
          <li className={styles.item}>
            <Link href="" data-text="item3">
              item3
            </Link>
          </li>
          <li className={styles.item}>
            <Link href="" data-text="item4">
              item4
            </Link>
          </li>
        </ul>
      </div>
    </header>
  );
}

// web/src/app/shared/core/header/header.component.ts
import { trigger, state, style, transition, animate } from '@angular/animations';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { fromEvent, Subscription, tap, throttleTime } from 'rxjs';
import { UserService } from '../../services/user/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  animations: [
    trigger('openClose', [
      // ...
      state('open', style({
        right: '0',
      })),
      state('closed', style({
        right: '-2000px'
      })),
      transition('open => closed', [
        animate('0.4s')
      ]),
      transition('closed => open', [
        animate('0.4s')
      ])
    ])
  ]
})
export class HeaderComponent implements OnInit {
  toogle = false;
  subject_profile: any = null;
  profile: any = null;

  isWhiteBackground = false;
  eventSub: Subscription;

  valueSearch = "";
  isShowSearchText = false;

  constructor(private userService: UserService, private router: Router) { }

  ngOnInit() {
    this.subject_profile = this.userService._profileChanged.subscribe((res: any) => {
      this.profile = res;
    });

    this.eventSub = fromEvent(window, 'scroll').pipe(
      throttleTime(70),
      tap(event => this.onScroll())
    ).subscribe();
  }

  toogleMenu() {
    this.toogle = !this.toogle;
  }

  ngOnDestroy() {
    if (this.subject_profile) {
      this.subject_profile.unsubscribe();
    }
  }

  onScroll() {
    const number = document.scrollingElement?.scrollTop || 0;
    if (number > 109) { 
      this.isWhiteBackground = true;
    } else {
      this.isWhiteBackground = false;
    }
  }

  showSearch() {
    this.isShowSearchText = !this.isShowSearchText;
    let searchEle = document.getElementById('search-text-header');
    if (this.isShowSearchText) {
      searchEle?.focus();
    } else {
      searchEle?.blur();
    }
  }

  search() {
    // call api search here
  }
}

<header [ngClass]="{'bg-white': isWhiteBackground }">
  <div id="header-content">
    <div id="left">
      <a id="logo" routerLink="/">
        <img src="assets/images/logo.png" alt="">
      </a>
    </div>
    <div id="right">
      <ul>
        <li class="search-box" [ngClass]="{'active': isShowSearchText}">
          <input 
            id="search-text-header"
            type="text" 
            [(ngModel)]="valueSearch" 
            class="search-text" 
            placeholder="Type to search..."
          >
          <button class="icon search-btn" (click)="showSearch()">
            <img src="assets/images/icons/ic_search-w.svg" alt="search">
          </button>
        </li>
        <!-- <li>
          <a routerLink="/auth/login" class="icon">
            <img src="assets/images/icons/ic_logout-w.svg" alt="search">
          </a>
        </li> -->
        <li>
          <div class="toggle">
            <div class="toggle-button" [ngClass]="{'on': toogle}" (click)="toogleMenu()">
              <span></span>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="side-nav" [ngClass]="{'open': toogle}">
    <div class="close-side-nav" (click)="toogleMenu()">
      <img
      src="assets/images/icons/ic_close.svg"
      alt="close-side-nav"
    />
    </div>
    <h2 class="side-nav__title">Menu</h2>
    <p class="side-nav__desc">メニュー</p>
    <ul class="side-nav__list">
      <li class="item">
        <a href="">item</a>
      </li>
      <li class="item">
        <a href="">item</a>
      </li>
      <li class="item">
        <a href="">item</a>
      </li>
      <li class="item">
        <a href="">item</a>
      </li>
      <li class="item">
        <a href="">item</a>
      </li>
      <li class="item">
        <a href="">item</a>
      </li>
    </ul>
  </div>
</header>
